server:
  port: 9527

spring:
  application:
    name: springcloud-zuul  #微服务名称

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul-9527 #注册中心描述信息
    prefer-ip-address: true #是否显示ip

info:
  app.name: ygl-springcloud
  company.name: www.baidu.com

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept  #将原来的服务名称换成我们自己的服务名称
    mydept.path: /mydept/** #这里是我们更改后的服务名称
  ignored-services: springcloud-provider-dept #忽略掉这个服务名称，不能再使用这个路径去访问了
  # ignored-services: “*” #这个是隐藏全部的服务名称
  prefix: /ygl #这个是统一访问前缀  设置公共前缀
