server:
  port: 8005

#mybatis配置
mybatis:
  type-aliases-package: com.ygl.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#mybatis配置
spring:
  application:
    name: springcloud-provider-dept  # 3个服务名称一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#eureka配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true  #显示当前主机地址
    instance-id: springcloud-provider-dept-8005  #修改eureka上的默认描述信息


#info配置
info:
  app.name: ygl-springcloud
  company.name: www.baidu.com